# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      ipvlan0:
        ipv4_address: '192.168.0.3' # Enable promiscuous mode for ipvlan (systemd create new oneshot service)
    ports:      
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      - "67:67/udp"
    environment:
      TZ: 'Asia/Singapore'
      FTLCONF_webserver_api_password: 'donothaveapasswordmaybeidk'
      FTLCONF_dns_listeningMode: 'all'
      FTL_NO_HISTORY: true
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
      #https://discourse.pi-hole.net/t/disable-query-logging-does-not-stop-all-logging/13300/9
networks:
  ipvlan0:
    external: true
