services:
  wg-easy:
    container_name: wg-easy
    environment:
      - WG_HOST=e24sotong.duckdns.org
      - PASSWORD_HASH=$$2a$$12$$r8pIJ7g64e1WxW6z.xMaie0EbOxmCyKGd2I2ZKHh/5Xru1vyNEsTG # WGisnOteaSY
    image: ghcr.io/wg-easy/wg-easy:latest
    volumes:
      - ~/VPN/wg-easy/config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
