services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: "duckdns"
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC-8
      - SUBDOMAINS=e24sotong
      - TOKEN=caa25a0d-4c72-4703-9a6b-2bb68ea83004
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - /home/hcm1e24/VPN/duck/config:/config
    restart: unless-stopped
