services:
  minecraft:
    image: itzg/minecraft-server
    container_name: "mcserver"
    environment:
      MEMORY: 3G
      TYPE: FABRIC
      EULA: TRUE
      ONLINE_MODE: FALSE
      DIFFICULTY: "Hard"
      SEED: "-4576639572579790409"
      LEVEL: "SOTONG_WORLD"
      VERSION: "1.21.4"
    networks:
      ipvlan0:
        ipv4_address: '192.168.0.2' # Enable promiscuous mode for ipvlan
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  ipvlan0:
    external: true
